//! Auto-generated from `options_gen.py`. Do not hand-edit; run the
//! generator instead. Hosts the libretro core options derive + the
//! preset/slot tables consumed by `input.rs`.

#![allow(clippy::needless_raw_string_hashes)]

// The `CoreOptions` derive macro expands to code referencing libc::c_char,
// SetEnvironmentContext, GenericContext, and a handful of `retro_*` sys
// structs — keep all three globs in scope or the macro fails to expand.
use rust_libretro::{contexts::*, proc::CoreOptions, sys::*, types::JoypadState};
use wie_backend::KeyCode;

#[options({
    "wie_input_layout",
    "Input > Layout",
    "Layout Preset",
    "Pick a preset or Custom for per-slot dropdowns below.",
    "Pick a preset or Custom for per-slot mappings.",
    "input_settings",
    {
        { "Phone Keypad (default)" },
        { "Numpad Only" },
        { "D-Pad Nav Only" },
        { "Custom" },
    }
})]
#[options({
    "wie_input_up",
    "Input > D-Pad Up",
    "D-Pad Up",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_down",
    "Input > D-Pad Down",
    "D-Pad Down",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_left",
    "Input > D-Pad Left",
    "D-Pad Left",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_right",
    "Input > D-Pad Right",
    "D-Pad Right",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_a",
    "Input > A (OK)",
    "A (OK)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_b",
    "Input > B (Clear)",
    "B (Clear)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_x",
    "Input > X (#)",
    "X (#)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_y",
    "Input > Y (0)",
    "Y (0)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_l",
    "Input > L (Soft Left)",
    "L (Soft Left)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_r",
    "Input > R (Soft Right)",
    "R (Soft Right)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_start",
    "Input > Start (Call)",
    "Start (Call)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_select",
    "Input > Select (Hangup)",
    "Select (Hangup)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_l2",
    "Input > L2 (1)",
    "L2 (1)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_r2",
    "Input > R2 (3)",
    "R2 (3)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_l3",
    "Input > L3 (7)",
    "L3 (7)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[options({
    "wie_input_r3",
    "Input > R3 (9)",
    "R3 (9)",
    "WIPI key sent when this RetroPad slot is pressed (used only when Layout = Custom).",
    "WIPI key sent when this slot is pressed (Custom layout only).",
    "input_settings",
    {
        { "None" },
        { "UP" },
        { "DOWN" },
        { "LEFT" },
        { "RIGHT" },
        { "OK" },
        { "LEFT_SOFT_KEY" },
        { "RIGHT_SOFT_KEY" },
        { "CLEAR" },
        { "CALL" },
        { "HANGUP" },
        { "NUM0" },
        { "NUM1" },
        { "NUM2" },
        { "NUM3" },
        { "NUM4" },
        { "NUM5" },
        { "NUM6" },
        { "NUM7" },
        { "NUM8" },
        { "NUM9" },
        { "HASH" },
        { "STAR" },
        { "VOLUME_UP" },
        { "VOLUME_DOWN" },
    }
})]
#[derive(CoreOptions, Default)]
pub struct Options;

pub const SLOTS: &[(&str, JoypadState)] = &[
    ("wie_input_up", JoypadState::UP),
    ("wie_input_down", JoypadState::DOWN),
    ("wie_input_left", JoypadState::LEFT),
    ("wie_input_right", JoypadState::RIGHT),
    ("wie_input_a", JoypadState::A),
    ("wie_input_b", JoypadState::B),
    ("wie_input_x", JoypadState::X),
    ("wie_input_y", JoypadState::Y),
    ("wie_input_l", JoypadState::L),
    ("wie_input_r", JoypadState::R),
    ("wie_input_start", JoypadState::START),
    ("wie_input_select", JoypadState::SELECT),
    ("wie_input_l2", JoypadState::L2),
    ("wie_input_r2", JoypadState::R2),
    ("wie_input_l3", JoypadState::L3),
    ("wie_input_r3", JoypadState::R3),
];

pub const PRESETS: &[(&str, &[KeyCode])] = &[
    (
        "Phone Keypad (default)",
        &[
            KeyCode::UP,
            KeyCode::DOWN,
            KeyCode::LEFT,
            KeyCode::RIGHT,
            KeyCode::OK,
            KeyCode::CLEAR,
            KeyCode::HASH,
            KeyCode::NUM0,
            KeyCode::LEFT_SOFT_KEY,
            KeyCode::RIGHT_SOFT_KEY,
            KeyCode::CALL,
            KeyCode::HANGUP,
            KeyCode::NUM1,
            KeyCode::NUM3,
            KeyCode::NUM7,
            KeyCode::NUM9,
        ],
    ),
    (
        "Numpad Only",
        &[
            KeyCode::NUM2,
            KeyCode::NUM8,
            KeyCode::NUM4,
            KeyCode::NUM6,
            KeyCode::NUM5,
            KeyCode::STAR,
            KeyCode::HASH,
            KeyCode::NUM0,
            KeyCode::LEFT_SOFT_KEY,
            KeyCode::RIGHT_SOFT_KEY,
            KeyCode::CALL,
            KeyCode::HANGUP,
            KeyCode::NUM1,
            KeyCode::NUM3,
            KeyCode::NUM7,
            KeyCode::NUM9,
        ],
    ),
    (
        "D-Pad Nav Only",
        &[
            KeyCode::UP,
            KeyCode::DOWN,
            KeyCode::LEFT,
            KeyCode::RIGHT,
            KeyCode::OK,
            KeyCode::CLEAR,
            KeyCode::HASH,
            KeyCode::NUM0,
            KeyCode::LEFT_SOFT_KEY,
            KeyCode::RIGHT_SOFT_KEY,
            KeyCode::CALL,
            KeyCode::HANGUP,
            KeyCode::NUM1,
            KeyCode::NUM3,
            KeyCode::NUM7,
            KeyCode::NUM9,
        ],
    ),
    ("Custom", &[]),
];

pub const PRESET_KEY: &str = "wie_input_layout";
pub const CUSTOM_PRESET: &str = "Custom";
pub const DEFAULT_PRESET: &str = "Phone Keypad (default)";

/// Build the active (JoypadState, KeyCode) mapping from the current
/// frontend variable values. Called once at init and whenever
/// `on_options_changed` fires.
pub fn resolve_mapping(ctx: &OptionsChangedContext) -> Vec<(JoypadState, KeyCode)> {
    let preset = ctx.get_variable(PRESET_KEY).unwrap_or(DEFAULT_PRESET);
    let preset_row = PRESETS.iter().find(|(n, _)| *n == preset);
    let mut out = Vec::with_capacity(SLOTS.len());
    for (i, (key, state)) in SLOTS.iter().enumerate() {
        // Custom layout (or any preset whose row is empty) reads per-slot
        // options; otherwise the preset row supplies the KeyCode directly.
        let kc = match preset_row {
            Some((_, row)) if !row.is_empty() => Some(row[i]),
            _ => ctx.get_variable(key).and_then(parse_keycode),
        };
        if let Some(kc) = kc {
            out.push((*state, kc));
        }
    }
    out
}

fn parse_keycode(s: &str) -> Option<KeyCode> {
    match s {
        "None" => None,
        "UP" => Some(KeyCode::UP),
        "DOWN" => Some(KeyCode::DOWN),
        "LEFT" => Some(KeyCode::LEFT),
        "RIGHT" => Some(KeyCode::RIGHT),
        "OK" => Some(KeyCode::OK),
        "LEFT_SOFT_KEY" => Some(KeyCode::LEFT_SOFT_KEY),
        "RIGHT_SOFT_KEY" => Some(KeyCode::RIGHT_SOFT_KEY),
        "CLEAR" => Some(KeyCode::CLEAR),
        "CALL" => Some(KeyCode::CALL),
        "HANGUP" => Some(KeyCode::HANGUP),
        "NUM0" => Some(KeyCode::NUM0),
        "NUM1" => Some(KeyCode::NUM1),
        "NUM2" => Some(KeyCode::NUM2),
        "NUM3" => Some(KeyCode::NUM3),
        "NUM4" => Some(KeyCode::NUM4),
        "NUM5" => Some(KeyCode::NUM5),
        "NUM6" => Some(KeyCode::NUM6),
        "NUM7" => Some(KeyCode::NUM7),
        "NUM8" => Some(KeyCode::NUM8),
        "NUM9" => Some(KeyCode::NUM9),
        "HASH" => Some(KeyCode::HASH),
        "STAR" => Some(KeyCode::STAR),
        "VOLUME_UP" => Some(KeyCode::VOLUME_UP),
        "VOLUME_DOWN" => Some(KeyCode::VOLUME_DOWN),
        _ => None,
    }
}
